# File: .github/workflows/workflow.yml

on: [push]
  #push:
  #  branches: main

name: Deploy to DEV

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: az deploy
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az webapp up --sku S1 --name test-python12345 --subscription "InnerEye Dev" -g InnerEyeInference